### ISSUE TITLE
Number formatting for Min ATK

### ISSUE THREAD

**Issue by ghost** [Grimy/Grimy.github.io#11]
I use standard formatting in game, but in zFarm my min ATK is now showing as "4.230831933875484e+37".

Would like to see standard formatting back.

**Comment by Grimy** [comment]
Thanks for the report!

Related issue: zFarm does not understand the newly introduced Alphabetic Notation. I’ll try to fix both at the same time.

**Comment by Grimy** [comment]
For the moment I just reverted to the previous behavior (always use Standard notation). Ideally, zFarm should use whatever notation is selected in the player’s save.

**Comment by Grimy** [comment]
Both Perky and zFarm now support all four notations (scientific, standard, engineering, alphabetic), and will use your favorite notation (reading it into your save file).
