### ISSUE TITLE
Formation: S, D

### ISSUE THREAD

**Issue by mFIND** [Grimy/Grimy.github.io#12]
I couldn't choose in which Formation I am when giving attack (z179), so I quess calculations for D and S formations are done with the same minATK value
Screen, probably nothing interesting:
https://gyazo.com/e8cfe7f8590c892f748561c8099bcaf6

**Comment by Grimy** [comment]
When inputting your attack, you have to give your minimum attack, in X, without the Titimp buff (this is explained in the tooltip).

Calculations correctly account for attack modifiers (if S and D used the same attack, S would always end up 2x better than D).

You probably don’t need to input your attack manually: pasting your save is the easier option.

**Comment by mFIND** [comment]
Oh, right, didn't notice the toolip change!
You are probably right.
Thanks for replying :)

**Comment by Grimy** [comment]
You’re welcome (=
