### ISSUE TITLE
Dark mode bug

### ISSUE THREAD

**Issue by Tadaisius** [Grimy/Grimy.github.io#13]
When you click on dropdown box, the font is invisible

**Comment by Grimy** [comment]
Could you please provide more details, and possibly a screenshot? Are you talking about this dropdown menu?
![dropdown](https://cloud.githubusercontent.com/assets/3199732/25780247/a0a401b0-3324-11e7-8116-b7954d352691.png)

**Comment by Tadaisius** [comment]
here you go

[image: Inline images 2]

**Comment by Tadaisius** [comment]
I am using chrome and adblock adblocker. It is fine on normal mode, but
when i switch modes, it also changes the colour of the font in dropdown too.

**Comment by Grimy** [comment]
Thanks for the details! It should be fixed, now.
