### ISSUE TITLE
Click “Optimize” several times will change the result.

### ISSUE THREAD

**Issue by ilwwli** [Grimy/Grimy.github.io#17]
Especially when change He weight to 0. It will first suggest to clear all perks, then change to an uncertain state which will give random suggestions.

**Comment by Grimy** [comment]
This sounds like a serious issue, but I can’t reproduce it. Could you share your save? Did you change anything apart from the He weight? Do you see errors in the JavaScript console?

**Comment by ilwwli** [comment]
[problem  .docx](https://github.com/Grimy/Grimy.github.io/files/1132916/problem.docx)
[save.txt](https://github.com/Grimy/Grimy.github.io/files/1132917/save.txt)

**Comment by Grimy** [comment]
Thanks for the extra info! I still can’t reproduce the problem, though (tried Firefox and Chrome). And I have no idea what could be causing it.

**Comment by ilwwli** [comment]
Have changed to firefox and it works well... Seems some addons should be responsible for it. Thanks a lot.
