### ISSUE TITLE
One hit zone seems wrong

### ISSUE THREAD

**Issue by Troger14** [Grimy/Grimy.github.io#18]
After z70 and I get the D formation it seems that the one hit zone in the calculator is lower than than the actual zone. The calculator dont say in wich zone I one hit everything in the D stance, just the X stance.

**Comment by Grimy** [comment]
Good catch. It doesn’t affect the main result in any way, but this message should still account for stances.

**Comment by Grimy** [comment]
This is fixed in v2.2, which is now online.
