### ISSUE TITLE
zFarm: Recalculating on same data gives different suggestions.

### ISSUE THREAD

**Issue by PriceChild** [Grimy/Grimy.github.io#19]
I've exported a save from the game and pasted it into zFarm.

Repeatedly hitting recalculate gives different recommendations.

Both the primary ("You should probably") but also secondary ("But _ with _% higher loot is better.") recommendations change.

Odd!

**Comment by Grimy** [comment]
This is expected. zFarm gets its results by simulating 24h of farming on each level. This involves a lot of randomness (enemy gen, damage range, crits), which usually causes the results to vary by 1 or 2% from one run to the next. When the optimal zone is a close call (as indicated by the “probably”), it can end up changing depending on RNG.

On the other hand, if you notice dramatic differences (> 5%) from one run to the next, that is definitely a bug.

**Comment by JoePricey** [comment]
Hmm ok, I'd expected averages to be calculated.

I hadn't kept too close an eye on how big the differences were, other than small. Will report back if I see something wild.
