### ISSUE TITLE
Map imp-orts and Wind empowerment display incorrectly

### ISSUE THREAD

**Issue by ShadowCyclonic** [Grimy/Grimy.github.io#20]
In zFarm, whenever I import my save, it sets my map imp-orts to my maximum imps purchased, not my number of map imps purchased. It also sets my Wind empowerment to 1, however my highest zone reached is 72, so I haven't gotten to nature empowerments at all.

**Comment by Grimy** [comment]
That sounds like a cache issue. Try force-refreshing the page (Ctrl + F5).

**Comment by ShadowCyclonic** [comment]
Seems like you were right, upon loading it up today and plugging my save in, wind empowerment was automatically set to zero, the only thing that I have to change is map imp-orts back to 1, but I only do that once and it doesn't change it back, thanks
