### ISSUE TITLE
Handle query strings with savefiles

### ISSUE THREAD

**Issue by davidmcclelland** [Grimy/Grimy.github.io#22]
My goal is to have a button in the Trimps window that would open perky or zfarm with my current save information. If perky would automatically handle a query string of the save file in the URL, then it would be as simple as adding buttons into the Trimps page. Ideally, both zfarm and perky would support it. 

Additionally, they could be smart enough that hitting the button for the other page would keep the query string and load my savefile. This could help when accidentally opening the wrong page or deciding not to farm and portal instead.

**Comment by Grimy** [comment]
That doesn’t sound like it would be generally useful. I’d accept a PR with the feature, but I won’t implement it myself if it only benefits one user.
