### ISSUE TITLE
Selecting Spire preset then back to Corruption/BP selects mass removals

### ISSUE THREAD

**Issue by PriceChild** [Grimy/Grimy.github.io#25]
Importing my save gives generally sensible suggestions, also when swapping between Corruption/BP presets.

If I select Spire, it suggests removal of things like Overkill, Resourceful, Meditation, Artisanry, Packrat, Motivation & Looting.

Now here's the bug: If I swap back to Corruption/BP, those same removal suggestions remain. i.e. I don't get the original suggestions.

I'm guessing one of the "Manual input" variables is being modified by the Spire preset but not reset by Corruption/BP?

Here's my save: https://gist.github.com/PriceChild/116c76b01e47c65efd702186b38ad9e7

**Comment by Grimy** [comment]
Thanks for the report! This will be fixed in the next version.

**Comment by Grimy** [comment]
Fixed in v2.1, which is now online.
