### ISSUE TITLE
Setting Anticipation level in Fixed perks is not reliable

### ISSUE THREAD

**Issue by aman-nizinski** [Grimy/Grimy.github.io#26]
With 3m He save setting Anticipation to 0 was ignored and setting it to other values wasn't always working properly. With Target zone 20 and Anticipation=0 Fixed the Optimizer suggested getting 13 levels in it.

**Comment by Grimy** [comment]
Thanks for the report!

This was not specific to Anticipation: fixing *any* Perk to 0 was completely ignored. This is now fixed.

Can you elaborate on “setting it to other values wasn't always working properly”? I can’t reproduce this part.
