### ISSUE TITLE
Getting no results, because "health is Infinity"

### ISSUE THREAD

**Issue by Nydaleclya** [Grimy/Grimy.github.io#27]
I am getting this error message: "lundefinedcundefined Error: health is Infinity". This happens if my Target Zone is under 470 as far as I tested.

Here is my save: https://pastebin.com/t74gE9tG

**Comment by Grimy** [comment]
That link gives me:

    This is a private paste. If you created this paste, please login to view it.

But I can reproduce just fine without your save, all I need is to set extremely high amounts of He.

This will be fixed in the next version. In the meantime, you can try setting caps on health perks as a workaround.

**Comment by Grimy** [comment]
Fixed in v2.1, which is now online.
