### ISSUE TITLE
Strange code block testing for map size

### ISSUE THREAD

**Issue by keybounce** [Grimy/Grimy.github.io#33]
I'm curious abou his block:

		if (cell % g.size === 99) {
			imp = max_rand;
			toughness = 2.9;
		}

I've never seen a "===" test before. One, and two equals signs, yes. But more than that, I'm curious what this test is supposed to do. It looks like it's supposed to see if you're on the next to last cell, and simulate a snimp at that spot.

But that would only be true for size 100 main zones, which can have a snimp in cell 99. For farming maps, the test should be a snimp in the last cell.

**Comment by Grimy** [comment]
See for example [this explanation](https://stackoverflow.com/questions/359494/which-equals-operator-vs-should-be-used-in-javascript-comparisons#359509) for the meaning of `===`.

I’m not sure why you mention snimps. Normal maps never have more than 75 cells. Bionic Wonderland has 100 cells, and the enemy in the last cell is a Robotrimp, which has a 2.9 health multiplier.
