### ISSUE TITLE
Nurseries and breeding speed.

### ISSUE THREAD

**Issue by keybounce** [Grimy/Grimy.github.io#35]
More on the repopulation speed issue:

	// Breed speed
	function breed() {
		let nurseries = building(2e6, 1.06) / (1 + 0.1 * min(magma(), 20));

I know that nurseries do not have a base cost of 2 million. I'm not sure that I understand the expected number of nurseries that a players expected to have, and I don't see anything here that is looking at the target zone (as in, more nurseries for a later target zone).

Can you clarify what perky is expecting in the way of nurseries?

**Comment by Grimy** [comment]
> I know that nurseries do not have a base cost of 2 million.

Nurseries have a base cost of 1M wood, 500K metal and 400K gems. I rounded that to 2M.

> I don't see anything here that is looking at the target zone

This line contains function calls to `building()` and `magma()`. Both functions look at the target zone.

Please use GitHub issues to report actual issues. If you want to ask about how the code works (or to just chat), you’re welcome to do that on Discord any time 😄 (I’m also Grimy on the Trimps Discord, in case you didn’t know)
