### ISSUE TITLE
Idea for a decay setting.

### ISSUE THREAD

**Issue by keybounce** [Grimy/Grimy.github.io#36]
Here is an idea for a decay setting for perky. Currently, perky over-values the effect of buying increased attack perks; decay gives you an increased attack already.

For the target zone, determine how long it takes to reach the last cell. Determine how many decay stacks have accumulated by this point, and this tells you the effective attack level, which can then be used to determine how many levels of attack perk to take.

Additionally, since the point of the target level is for things such as running void maps, an option to say I'm going to run a point map at this level. Now the target would be to run a 200 difficulty void map first, and the target zone second.

**Comment by Grimy** [comment]
> perky over-values the effect of buying increased attack perks

Perky values attack perks exactly as much as you tell it to. If you’re not happy with it, you can increase “Weight: Attack” in the settings.

> For the target zone, determine how long it takes to reach the last cell.

This very much depends on the way you play, and there is no way Perky can possibly guess that.

> Additionally, since the point of the target level is for things such as running void maps, an option to say I'm going to run a point map at this level. Now the target would be to run a 200 difficulty void map first, and the target zone second.

I didn’t understand any of this. What’s a point map?

**Comment by keybounce** [comment]
Simple: a voice to text error that got past proofreading. Should have been void map.

So here's a little more detail of what I'm describing. If I is choose the preset for zones one through 60, and I'm running decay, then the values that come out of perky give me horrific overkill on my attack, and my health, that could go into looting or production, or reducing the cost of upgrades.

I took a look at the code in perky. I did not understand most of it. But as far as I can tell, it's making assumptions about how much housing, how much attack, etc. you will have at your target zone. Equally, you can simulate running through that target zone with the number of trimps, and expected attack and health. Therefore, it's possible to tell if you are going to make it through the end while you are still getting a bonus from decay, and whether or not you are able to clear a void map as well.

**Comment by Grimy** [comment]
> the values that come out of perky give me horrific overkill on my attack, and my health, that could go into looting or production, or reducing the cost of upgrades.

But why would you need resources, if not to increase attack and health? That’s all they’re good for, in the end.

> Equally, you can simulate running through that target zone

No, I can’t. If you can do it, feel free to submit a PR.

**Comment by keybounce** [comment]
> But why would you need resources, if not to increase attack and health? That’s all they’re good for, in the end.

My goal is to collect helium.

I can do this by increasing looting, which directly affects my income; by increasing the universe speed, which allows me to kill things faster, and reach the end of the zone faster, which -- only in decay -- give me an increased attack bonus against stronger enemies at the end of the zone; by buying increased population, which gives me higher production, additional coordinations, and higher loot income (all of which let me buy more tiers); by reducing the cost of additional tiers; by buying increased attack (and to some extent, increased defense) which lets me continue to defeat zones even when I can no longer buy coordinations, and/or equipment; and finally -- but not in decay -- farming maps (see looting) to afford additional stuff.

I do not pretend to understand the code in either Perky or zFarm. Perky looks like it is making assumptions about what you are likely to have at a given zone, how your population will have scaled, etc. When running Decay, three assumptions change. First, you don't have farming as a significant option. Second, speed is (sort of) equal to attack power. Third, speed is sort of equal to looting, with an inverse behavior -- your production is significantly higher at the beginning of the map, but the faster you finish the map, the less production (and bonus production) you get.

zFarm looks like it is simulating attacks on a map. Repeated runs of zFarm with the same inputs do not give the exact same output. If I understood how zFarm handles the different map types, I would guess that asking it for a length 100 zone, of strength 100 (instead of the default length 27, strength 80), with the right types of monsters defined, would be able to determine what running the main zone of the map looks like. A similar operation, with nastier monsters, of length 100, strength 200 would approximate void maps.

Based on that last paragraph, it should be possible to determine the length of time it takes to complete a void map, and the main zone, along with the assumptions of population, expected attack strength, etc.; and make sure that the total time for the zone is under the "slow down" point of decay (where attack value has dropped to below normal).

Ideally, I would say that my Perky targets are 100 helium, zero attack, zero defense. Helium is ultimately the only thing that I value at the end of a run.

If I am running decay, then I am reaching the point where I have enough gymmystic that my defense is my block. Putting wood into block is more effective than trying to put metal into hit points, or even wood into shield. And the default values that I get from Perky using the zone 1 to 59 preset has my offense so overpowered that I can continue to go five zones after I stop buying any weapons (and probably one zone after I stop getting coordination) without any slow down. Note that while perky asks me how much I value an increase in my offense, it does not take into account the increase in offense that I already have from my achievements, nor the increase in offense that I get from Decay.

By manually turning down my attack strength, defense strength, and hit point perks, I can buy additional looting (direct increase in helium, increase in map loot), carpentry (more people -- more loot, more coordinations), and/or reduced upgrade cost (one or two more weapons upgrades).

The difference between being able to enter zone 60 (cell 23 is the farthest I have gotten), and being able to clear zone 60 or 61 is a huge amount of helium. (Based on what I have been told in the Discord chat). Equally, Decay vs. Balance seems to favor Decay for farming helium. Since it looks like massive repeats of decay runs is important, and decay doesn't have the same assumptions as a normal run, it would seem that a decay-specific setting would be important.

**Comment by Grimy** [comment]
> Note that while perky asks me how much I value an increase in my offense, it does not take into account the increase in offense that I already have from my achievements, nor the increase in offense that I get from Decay.

It doesn’t because *that’s totally irrelevant for what Perky is doing*. Perky has absolutely no idea how much attack you’ll have, nor does it care. It only knows about the *relative* increases to attack you get from perks, not the grand total (which is anyway impossible to know in advance).

> it should be possible to determine the length of time it takes to complete a void map, and the main zone, along with the assumptions of population, expected attack strength

There’s no such thing as “expected attack strength”, only “expected extra strength from perks”.

> By manually turning down my attack strength, defense strength, and hit point perks, I can buy additional looting, carpentry, and/or reduced upgrade cost.

Swapping power and toughness for carpentry and artisanistry is a mistake. Perky knows exactly how much extra attack/hp you’re getting from the extra coordinations and gear those perks afford you, and values them accordingly.

Swapping power and toughness for looting is very reasonable, but if that’s what you want to do, why not simply increase “Weight: Helium” in the settings?
