### ISSUE TITLE
Territory bonus miscalculation?

### ISSUE THREAD

**Issue by keybounce** [Grimy/Grimy.github.io#37]
The territory bonus for trimps is calculated by this:

		let territory = add(Trumps, 20) * zone;

The thing is, this doesn't look like it takes into account your base 10 trimps per level. So if I am on zone 40, it would be 400+ the trimps bonus, and this underestimates that by 400.

**Comment by Grimy** [comment]
This amount is multiplied by 10 on the very next line. This makes 10 trimps per zone, plus a 20% additive bonus per level of Trumps, which is the correct calculation.
