### ISSUE TITLE
zfarm not working properly. always showing 62.5 cells/s

### ISSUE THREAD

**Issue by Molodude** [Grimy/Grimy.github.io#40]
Every time I paste my save, it is always showing that I am clearing 62.5 cells/s in D and S, no matter what. I am not touching any of the manual inputs at all.
![image](https://user-images.githubusercontent.com/36315714/36451777-348afa54-1660-11e8-9306-ebee5e92b438.png)

**Comment by Grimy** [comment]
Thanks for the report! This is now fixed.
