### ISSUE TITLE
DG housing wrongfully taken into account for restart

### ISSUE THREAD

**Issue by jrynd** [Grimy/Grimy.github.io#41]
Save at https://pastebin.com/4KzeJQv0

Pasting this into Perky fills in the DG housing. But this should only be relevant if we're doing a mid-run respec. I'm not. Changing the DG housing field to 0 and re-calculating gives different results.

**Comment by Grimy** [comment]
DG housing is always relevant, not just for mid-run respecs. Manually changing it to 0 will give incorrect results (unless you actually get 0 housing from DG in the next run).
