### ISSUE TITLE
zfarm Suggestion: Calculate for D-S stancedance

### ISSUE THREAD

**Issue by jrynd** [Grimy/Grimy.github.io#45]
Usually, you get a better resource earn rate if you start out in D and switch over to S right before you get to the cell with the cache. Can you add an option to zfarm to calculate the effectiveness of this (extremely handson) stancedance for each level?

**Comment by Grimy** [comment]
This is borderline cheating and I don’t want to encourage it, so I won’t implement this feature. Anyway, you can just use the optimal D zone for this, it’ll usually be the same as the optimal D+S zone.
