### ISSUE TITLE
QoL on removal perks

### ISSUE THREAD

**Issue by Benthem** [Grimy/Grimy.github.io#5]
I think it would help with knowing whats getting decreased if the perks or the text of the perks that are 'to be removed' are highlighted in a red colour.

**Comment by Benthem** [comment]
Implemented in https://github.com/Grimy/Grimy.github.io/commit/87f32b137a74c4f7704866155d3f8bdfddf89c97

**Comment by Grimy** [comment]
Thanks for the suggestion!
