### ISSUE TITLE
can't see spire(respec) preset

### ISSUE THREAD

**Issue by jeremie2047** [Grimy/Grimy.github.io#50]
The spire(respec) is just inexistant on my perky even tho i need it was there some time ago. I cleared my cache+cookies and tried using it on firefox but 
i still have the same issue.
![perky](https://user-images.githubusercontent.com/39674140/40587395-7b2203cc-619c-11e8-8b3e-1ff7c3652b5d.jpg)

**Comment by Grimy** [comment]
It’s hidden on purpose, to help prevent people mistakingly using it. This respec removes almost all income perks to scrounge up slightly more damage and health, so doing an entire run with it is very much not recommended. Get to z200 normally, farm for all the gear you want, and *then* respec (that’s why the preset is called “Spire *respec*”).
