### ISSUE TITLE
Cunning

### ISSUE THREAD

**Issue by RacinanteOpus** [Grimy/Grimy.github.io#51]
Why does Perky recommend multiple levels in Cunning when Capable is not high enough to gain any additional experience for Fluffy?

**Comment by Grimy** [comment]
I fixed this issue two days ago. Can you refresh and try again?

**Comment by RacinanteOpus** [comment]
Certainly.  If I encounter the issue again, I'll let you know.  This last happened to me more than three days ago, so my timing looks to be a bit off.  Thanks!
