### ISSUE TITLE
zFarm doesn't take into account Obliterate challenge

### ISSUE THREAD

**Issue by am0d** [Grimy/Grimy.github.io#58]
It appears that zFarm doesn't take into account the increased health and attack of enemies in the Obliterate challenge.
I get told to farm at zone 39 when I'm running zone 30, even though I can barely survive 2 attacks in zone 30 because of the increased damage of the enemies.

Sample save at zone 30, where I can barely beat enemies 1 or 2 zones ahead: https://pastebin.com/CwFci9mU

**Comment by Grimy** [comment]
> zFarm doesn't take into account the increased health and attack of enemies in the Obliterate challenge.

It does, though.

> I get told to farm at zone 39

Pasting your save into zFarm gives me the following result screen:

![0](https://user-images.githubusercontent.com/3199732/43617685-2dee218c-96c4-11e8-852d-9adf4dddcdcb.png)

As you can see, the advice is to farm z23 or z26, far from z39. I’m not sure what could have happened for you to get different results.

**Comment by am0d** [comment]
This is what I get when I paste the linked save into zFarm (using the version at https://grimy.github.io/zfarm.html):
![image](https://user-images.githubusercontent.com/139484/43619335-40159d46-969b-11e8-935f-b8bba0a83b72.png)

**Comment by Grimy** [comment]
Alright, there was indeed a bug, though it wasn’t related to Obliterate. It should be fixed, now.

**Comment by am0d** [comment]
Thanks a lot for the quick response.

**Comment by Grimy** [comment]
You’re welcome, thank you for the report!
