### ISSUE TITLE
Occasionally doesn't show current zone stats.

### ISSUE THREAD

**Issue by nathanhaines** [Grimy/Grimy.github.io#59]
Every so often, I'll import my save and not get stats for the current zone, although I expect it to be on listed even if it's suboptimal.  Example, I'm on zone 185 but only get stats for 184 maps: https://pastebin.com/bcgdNKPC

**Comment by Grimy** [comment]
You have Map Reducer. There’s no reason ever to farm on the current zone once you have Map Reducer. That’s why it isn’t shown.
