### ISSUE TITLE
leveling me capability

### ISSUE THREAD

**Issue by ajrock** [Grimy/Grimy.github.io#62]
Hey man! Big fan of your work. Looks like capability was quickly coded in when it came out, fair 'nuff, but right now if you try to increase capability level (e.g. you're running challenge2 or whatever and want to get experience in fluffy for use later or something) beyond the recommendation, the script does not reserve helium for it, again probably because right now you only use 'leftover' helium to fund the thing. This would probably be a pain in the ass to change, so I understand if it's not a priority :)

**Comment by Grimy** [comment]
Capability? Do you mean Capable? Have you tried adding `Capable=9` (or whatever level you want) to your fixed perks?

**Comment by ajrock** [comment]
Here's a quick snapshot I took:

https://pasteboard.co/HMIRu3c.png

I hope it shows accurately that
a) it soes not accept Capable=5 as input, needs a space between.
b) Then, it says I cannot afford it, despite being the only fixed perk.

**Comment by Grimy** [comment]
a) You typed `Capable=5` in the “Unlocked perks” box. Don’t do this. Type it in the “Fixed perks” box, as I said above.

b) Remember that each level of Capable is 10x more expensive than the previous one.

**Comment by ajrock** [comment]
Oh my god, I am an absolute dunce. Thank you very much and I'm going to
disappear in shame now.
