### ISSUE TITLE
zFarm: 1 Level progress sugestions

### ISSUE THREAD

**Issue by puggan** [Grimy/Grimy.github.io#63]
How should I compare the loot at current level, with the loot if I progress an level?

Senario:
If i paste my save export, and it says that I'm earning 197 lootunits on level 72.
If i then manualy change the "World zone" to 73, it now says I can earn 187.7 lootunits on level 73.

I guess thats not taking the increased level of loot in account, so thous 187.7 have [50% more value](https://trimps.wikia.com/wiki/Loot#Part_3:_Mega_Book_Multiplier),

So if I want to compare thous 2, I should compare 187.7 * 1.5 with 197?
So I get 43% more loot if I progress to level 73.

Can there be some notice about recomendation to progress when a higher world zone gives more loot?
Or is it so simple as a higher worldzone always give better loot?

**Comment by Grimy** [comment]
Past z60, higher world zone always gives better loot. There already is a "you should be pushing rather than farming" notice, but it’s only used in extreme cases: don’t think that you shouldn’t be pushing just because you didn’t get that notice.
