### ISSUE TITLE
Imports fails in v4.11.2

### ISSUE THREAD

**Issue by puggan** [Grimy/Grimy.github.io#66]
When trying to import the Perks from Perky, they get the wrong values ingame.

Perky:
![Screenshot from 2019-05-10 16-39-16](https://user-images.githubusercontent.com/866668/57535310-3eca6c80-7342-11e9-9193-45b922d8cc6f.png)

Trimps:
![Screenshot from 2019-05-10 16-39-10](https://user-images.githubusercontent.com/866668/57535311-3eca6c80-7342-11e9-9bb3-f8a57d45d3e8.png)

Save file:
[Trimps Save P183 Z21.txt](https://github.com/Grimy/Grimy.github.io/files/3166940/Trimps.Save.P183.Z21.txt)

Perks-code:
```
N4IgMg9hAuCWB2BzA+gSVSAXABgDQgGEBDAJwAcBTeaEgTzQx3wFkZYA3IuCeBrAJmwAOfAAUIAdwok+mAMwBWAJz4AKhACuiABbwKAZ32ylAFnzEyRAEYAbCljyEN8eAkQPzGkrE36PhGyJDWn8AeXZpAGtYGxssADZ8ACUDTRIAYwoAMw04zABGRwIoEgATBC4KUoEzEABlWDJtHggbCEQQ+XwAQWpYdMauH3gsQuSDGNgqTKw5RJBmKthoIZ4sAHZxu2o7Qz1DUaLSSmo6LAV+HpI4fSJXfRpOkxEQJLvEewLHbsRJ6E7BPgAEJEZb+VQkDQAWzIfnkjlE2mkEChPAMWBM+TERHSkRIXFm81YcE43BGmAUWJA4ikJHOtXUWl0BjhJk24CgcCQ5yUAF8gA
```

**Comment by Grimy** [comment]
I don’t know what causes this. Try clearing your cookies, that should get it working again. (If you don’t want to clear cookies for all sites, you can follow [this guide](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox?redirectlocale=en-US&redirectslug=delete-cookies-remove-info-websites-stored#w_delete-cookies-for-a-single-site), or just load Perky, open the JS console, and run `localStorage.clear()`).

**Comment by puggan** [comment]
Had no cookie for that site, but after clearing the local storage, it started to work again.

Was testing in incognito-mode before posting the issue, but maybe I only but trimps in incognito (=not perky).

**Comment by AnOctopus** [comment]
I'm also experiencing this issue, and have been for a few weeks, and it persists even after clearing local storage. It only happens on firefox, it works fine in chromium, even though they both show the same perk loadout they produce different strings.

Save: 
[Trimps Save P115 Z61.txt](https://github.com/Grimy/Grimy.github.io/files/3479629/Trimps.Save.P115.Z61.txt)

Correct perk string:
`N4IgKgpgdghgxgSwC4E8QC4AMAaEBhAJ2QThgBtk0tcBRARwFdzKMcQAFIgZwFtzXcAGQD2wpAigBzAPoBJWRgCsAdlx4YBAA7QkBFHIXoAzAEZcAWTEIAbjHHCoBjCYBsZjsIDuEAk/QAmAE5VcGEGSQALKAguLj9ld3VNGAAjMggBfAYoKAlJTLwGIjCuArIYWKo2AHlrHwBrBDIyDBdcACUYsII4CAAzBhb0QLVRAgATCTsIcYx/f1wAZQRNCIdhMmFJKiNcAEEocURk+yhnNk6uJoRoXowjRQsZ5DsEBwwQzvTD9Njo2POag02kOeiU7j2BHEXBguS4uioABZPrDJBl0CY2HtJNdUHM2AAhGDITJgAgMHiaUrGNjsCI+YQ8BwxDCI2nweoEOz3R4gSziWynJS0rw+JS7ULhKIxamItogERWKRKAAcAF8gA==`

Incorrect FF perk string:
`N4IgMg9hAuCWB2BzA+gSVSAXABgDQgGEBDAJwAcBTeaEgTzQx3wFkZYA3IuCeBrPEAAUIAdwok+TEABUIAV0QALeBQDOqyQOJkiAIwA2FfvgJz48BImOE5JWPNXWC+outrWA8u3EBrWPv1rACU1eRIAYwoAMzlAzABGEygSABMELgoUrHiBAGVYMkUeCH0IRHcpAEFqWHCCrnt4bIEQ1X9YKkisACYAdhZM2GgGnix+kBDDakN1FXVmk1JKajosABYBSpI4VSILVRoKgGZxoL3EIwTNxHboCu6BACEiIetpEjkAWzJHTG7u/CCRTiCCfHhqLBHI6AojhHwkLg9casOCcbhNTBrRJCUTidZrfCyBTKNS/I4ADnwkDYSHWAE4AL5AA`

![Results of importing perk string](https://user-images.githubusercontent.com/7356217/62672166-68e5f780-b94e-11e9-9ce7-17213d4434e4.png)
As far as I can tell, the perk string in FF is always for the same amount of helium and I suspect it's always exactly the same, so it seems like perky has gotten stuck producing the same one every time somehow persisting through local storage clears and browser restarts.

**Comment by AnOctopus** [comment]
Looking at this a bit more, I noticed that when I select the `#perkstring` element, the defaultValue, innerHTML, etc all have the correct perk string, but the `value` is the incorrect one. Testing in the console indicates that `$('#perkstring').innerText = 'foo'` changes the text in the textarea box on chromium but not FF.

**Comment by Grimy** [comment]
Thanks a lot for investigating this! I’ve pushed a fix, please let me know if it solves the issue on your end.

**Comment by kasi-mir33** [comment]
I have tried the import/export function for the first time just now and I have experienced the same issue. So I assume that fix wasn't enough. 

I couldn't even find a cookie to delete for grimy.github.io and clearing the local storage didn't do anything either. 

Works fine on Chrome.

**Comment by AnOctopus** [comment]
It looks like it's working for me now.

**Comment by Grimy** [comment]
Thanks for confirming! I’m closing this as fixed.

@kasi-mir33 : you were most likely using a version from before the fix. Just refresh and you should be good.
