### ISSUE TITLE
Farming: *fragment* farming is different

### ISSUE THREAD

**Issue by keybounce** [Grimy/Grimy.github.io#70]
Fragment farming does not follow the same income rate as other resources.

As a quick example, just look at Trimple of Doom for late-game players. You'll get non-zero income on most resources, but zero fragment income from flutimps. 

If someone wants to farm a depth map for fragments, the income difference means that what's best for food/wood/metal isn't necessarily the same as fragments.

Additionally, the FA modifer is not an even speed increase. If you are taking more than 1 or 2 shots per enemy, you get more of a speed up -- especially if you already have hyperspeed -- because the per-shot rate is significantly less than the per-cell rate.

The result? FA depth for frags is NOT the same calculation as cache gardens for resources.

**Comment by Grimy** [comment]
> Fragment farming does not follow the same income rate as other resources.

It does. It’s affected by all the same multipliers as the other resources.

> As a quick example, just look at Trimple of Doom for late-game players. You'll get non-zero income on most resources, but zero fragment income from flutimps.

Yes, as expected. The base fragment income is low enough that applying 600 low map level penalties to it is enough to get it down to 0, while the base income for other resources is too high for that.

> Additionally, the FA modifer is not an even speed increase.

Indeed. If you care about that, you can change "Attack speed" from 3.585 to 2.585 in the advanced options. Don’t forget to set the Biome to Depths as well.

**Comment by keybounce** [comment]
Hmm. I thought that the income did not go up by 60% per zone (base), but by something like the sqrt(zone) -- formula for map drops is different than the rest of the loot.

Alright, will change that attack speed manually then. When I need frags, I need frags.
