### ISSUE TITLE
New perks in u2 causing same old issue

### ISSUE THREAD

**Issue by Sholdice** [Grimy/Grimy.github.io#78]
2 new perks in u2 "Hunger" and "Frenzy" causing the same issues as previously that break everything.

Basically same problem and solution as the greed stuff from previous PR: https://github.com/Grimy/Grimy.github.io/pull/75

**Comment by Grimy** [comment]
Fixed by e00a1d3. The same solution as #75 would break again on every new U2 perk, so Perky now properly filters out U2 perks.
