### ISSUE TITLE
Perky not not correctly optimizing health between Resilience, Toughness, and Toughness II

### ISSUE THREAD

**Issue by pfayze** [Grimy/Grimy.github.io#86]
Perky is recommending 33 Resilience, 44 Toughness, and 214 Toughness II.
With -6 Toughness II, I can get +1 Resilience, a positive net in both health and helium.

<img width="1404" alt="Screen Shot 2022-01-04 at 2 37 04 PM" src="https://user-images.githubusercontent.com/4940277/148133511-804124d9-1c70-4204-b86a-1e44900dcb83.png">

**Comment by Grimy** [comment]
Fixed by 3a45508.
