### ISSUE TITLE
Perky does not see some helium

### ISSUE THREAD

**Issue by jaaaco-j** [Grimy/Grimy.github.io#97]
HZE is 170, did not unlock overkill yet. Perky is missing exactly 299k helium in the perk distribution even though the "total helium" field has correct numbers. not really sure what to do about this

![image](https://github.com/Grimy/Grimy.github.io/assets/48223505/78bd5799-f540-4f28-937d-a151b478c039)

![image](https://github.com/Grimy/Grimy.github.io/assets/48223505/85d6ba0c-ff2c-46ce-a655-456b2f794695)

(note the difference between leftover helium)

**Comment by Grimy** [comment]
Most likely 299k is the amount of helium you gained during that run, and you had the "Mid-run respec" checkbox ticked, which prevents spending helium gained during the run.

If that’s not actually what happened, it’s a bug, but I would need the paste to debug it, and I imagine you no longer have it. Still, thanks for the report, and sorry it took me this long to notice it! For bug reports, you can ping me in the Trimps discord for a faster reply.

**Comment by jaaaco-j** [comment]
the 299k was missing for multiple runs with mid run respec turned off. it fixed itself when i unallocated all helium from perks, seems it was a one off as it did not happen again
